name: CI
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - run: sudo apt install -y cowsay
      - run: dpkg -L cowsay
      - run: mkdir -p ~/bin
      - run: cp /usr/games/cowsay ~/bin/cowsay
      - run: cargo install cargo-audit
      - run: cargo build
      - run: which cargo
      - run: pwd
      - run: ls -lA
      - run: ls -lA ~/
      - run: ls -lA ~/bin
      - uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo
            ${{ github.workspace }}
            ~/bin
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}

  audit:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo
            ${{ github.workspace }}
            ~/bin
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}
      - run: cargo audit

  run:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo
            ${{ github.workspace }}
            ~/bin
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}
      - run: echo "$HOME/bin" >> "$GITHUB_PATH"
      - run: echo $PATH
      - run: echo $GITHUB_PATH
      - run: cargo run

  teardown:
    runs-on: ubuntu-latest
    needs:
      - audit
      - run
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: gh cache --help
      - run: gh cache list
      - run: gh cache delete --key cache-${{ github.run_id }}-${{ github.run_attempt }}
