name: CI
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: sudo apt install -y cowsay
      - run: which cowsay
      - run: cargo install cargo-audit
      - run: which cargo
      - uses: actions/cache/save@v4
        with:
          path: /
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}

  audit:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: /
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}
      - run: cargo audit

  run:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: /
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}
      - run: cargo run
